<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-08-02 06:11
=======
# Generated by Django 5.1.1 on 2025-08-03 10:53
>>>>>>> e391402f781a33e9b0bb4b4d1528f0baf4c6349e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
