# Generated by Django 5.1.1 on 2025-05-16 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0002_eventcategory_eventfeedback_eventregistration_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'organizer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last date to register'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the event starts'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ems_app.eventcategory'),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ems_app.event'),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_feedback', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ems_app.event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='users.customuser'),
        ),
        migrations.AlterUniqueTogether(
            name='eventfeedback',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'participant')},
        ),
    ]
