# Generated by Django 5.1.1 on 2025-07-28 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0004_eventanalytics_eventcomment_eventimage_eventreminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ems_app.eventcategory'),
        ),
    ]
