# Generated by Django 5.1.1 on 2025-07-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0006_rename_ems_app_eve_categor_5748dc_idx_ems_app_eve_categor_4dbbf1_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='ems_app_eve_categor_5748dc_idx',
            old_name='ems_app_eve_categor_4dbbf1_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('technical', 'Technical'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('fest', 'College Fest'), ('orientation', 'Orientation'), ('club', 'Club Activity'), ('competition', 'Competition'), ('guest_lecture', 'Guest Lecture'), ('placement', 'Placement Drive'), ('social', 'Social Gathering')], default='academic', help_text='Select the event category', max_length=20),
        ),
    ]
