# Generated by Django 5.1.1 on 2025-07-31 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0007_rename_ems_app_eve_categor_4dbbf1_idx_ems_app_eve_categor_5748dc_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='ems_app_eve_categor_4dbbf1_idx',
            old_name='ems_app_eve_categor_5748dc_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ems_app.eventcategory'),
        ),
    ]
