# Generated by Django 5.1.1 on 2025-09-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0005_alter_event_category'),
        ('ems_app', '0009_eventlocation_alter_event_location'),
    ]

    operations = [
    ]
