# Generated by Django 5.1.1 on 2025-09-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0010_merge_20250915_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ems_app.eventcategory'),
        ),
    ]
